Repository elastic/elastic-otel-java, pull requests merged in 2024-08, with the labels that each got.

#342 [release] release-step-2 0.5.0
  version.properties
Labels: agent-java

#343 [release] release-step-4 0.5.0
  version.properties
Labels: agent-java

#344 Add update-cli task to automatically update upstream agent
  .ci/updatecli.d/bump-upstream-agent-version.yml
  .github/workflows/updatecli.yml
Labels: agent-java

#345 Update upstream OpenTelemetry agent dependencies to 2.6.0
  gradle/libs.versions.toml
Labels: dependencies, agent-java

#348 Remove enforced delta temporality for metrics
  custom/src/main/java/co/elastic/otel/ElasticAutoConfigurationCustomizerProvider.java
  custom/src/main/java/co/elastic/otel/ElasticMetricExporter.java
  licenses/byte-buddy-dep-1.14.18.jar/META-INF/LICENSE
  licenses/byte-buddy-dep-1.14.18.jar/META-INF/NOTICE
  licenses/more-licences.md
Labels: agent-java

#354 Don't label renovate PRs and disable dependabot for java deps
  .github/dependabot.yml
  .github/workflows/labeler.yml
Labels: agent-java

#353 Remove unused and invalid spotless dependency declaration
  gradle/libs.versions.toml
Labels: agent-java

#366 Replace groovy with kotlin for root project
  agent/entrypoint/build.gradle.kts
  agentextension/build.gradle.kts
  bootstrap/build.gradle.kts
  build.gradle
  build.gradle.kts
  buildSrc/src/main/kotlin/elastic-otel.agent-packaging-conventions.gradle.kts
  buildSrc/src/main/kotlin/elastic-otel.java-conventions.gradle.kts
  buildSrc/src/main/kotlin/elastic-otel.spotless-conventions.gradle.kts
  resources/build.gradle.kts
  smoke-tests/build.gradle
  smoke-tests/test-app-war/build.gradle.kts
  smoke-tests/test-app/build.gradle.kts
  testing-common/build.gradle.kts
Labels: agent-java

#371 Add back accidentally removed nexus publishing plugin
  build.gradle.kts
Labels: agent-java

#372 DRY: Move autoservice and common test dependencies to convention
  buildSrc/src/main/kotlin/elastic-otel.java-conventions.gradle.kts
  common/build.gradle.kts
  custom/build.gradle.kts
  inferred-spans/build.gradle.kts
  jvmti-access/build.gradle.kts
  resources/build.gradle.kts
  testing-common/build.gradle.kts
  universal-profiling-integration/build.gradle.kts
Labels: agent-java

#328 [docs] Prepare docs
  NOTICE
  README.md
  agent/build.gradle.kts
  build.gradle.kts
  custom/src/main/java/co/elastic/otel/config/LegacyConfigurations.java
  custom/src/test/java/co/elastic/otel/config/ConfigurationExporterTest.java
  custom/src/test/resources/configure.asciidoc.ftl
  custom/src/test/resources/migrate.md.ftl
  docs/configure.asciidoc
  docs/configure.md
  docs/get-started.asciidoc
  docs/get-started.md
  docs/index.asciidoc
  docs/landing-page.asciidoc
  docs/migrate.md
Labels: documentation, agent-java

#375 Update upstream OpenTelemetry agent dependencies to 2.7.0
  gradle/libs.versions.toml
Labels: dependencies, agent-java

#380 Deprecate elastic config prefix for inferred spans
  inferred-spans/README.md
  inferred-spans/src/main/java/co/elastic/otel/profiler/InferredSpansAutoConfig.java
  inferred-spans/src/test/java/co/elastic/otel/profiler/InferredSpansAutoConfigTest.java
  testing/integration-tests/inferred-spans-test/build.gradle.kts
Labels: agent-java

#381 update licences
  licenses/byte-buddy-dep-1.14.19.jar/META-INF/LICENSE
  licenses/byte-buddy-dep-1.14.19.jar/META-INF/NOTICE
  licenses/more-licences.md
Labels: agent-java

#379 add specific config options to config doc
  docs/configure.md
Labels: agent-java

#384 pull the plug on breakdown metrics
  README.md
  custom/breakdown-metrics.md
  custom/src/main/java/co/elastic/otel/ElasticAgentListener.java
  custom/src/main/java/co/elastic/otel/ElasticAutoConfigurationCustomizerProvider.java
  custom/src/main/java/co/elastic/otel/ElasticBreakdownMetrics.java
  custom/src/main/java/co/elastic/otel/ElasticExtension.java
  smoke-tests/src/test/java/com/example/javaagent/smoketest/AgentFeaturesSmokeTest.java
  testing/integration-tests/universal-profiling-test/build.gradle.kts
Labels: agent-java

#389 Update README.md
  README.md
Labels: agent-java

#388 prepare GA release
  README.md
  jvmti-access/src/test/java/co/elastic/otel/UniversalProfilingCorrelationTest.java
  version.properties
Labels: agent-java
